// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://migptxsjdvnwauvspfvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1pZ3B0eHNqZHZud2F1dnNwZnZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NDI0MTUsImV4cCI6MjA3MTMxODQxNX0.e_7JWYIMoB29vBi9Rov0mPCaC0VL-mcKfjJnBPrRcpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});